### ISSUE TITLE
Shader error in "delta_t_display_renderer" when using Nvidia GPU

### ISSUE THREAD

**Issue by fanpeng-kong** [neuromorphic-paris/tutorials#37]
Hi Alex,

I run into the following error while running the **atis_event_stream_viewer** example when using the Nvidia GPU on my laptop:

> terminate called after throwing an instance of 'std::logic_error'
  what():  Shader error: 0(16) : error C1101: ambiguous overloaded function reference "log(uint)"
    (0) : lowp float log(lowp float)
    (0) : mediump float log(mediump float)
    (0) : float log(float)

However, the problem is gone when I switch to the integrated Intel GPU on my laptop.

It looks like the problem is from the function [`virtual void check_shader_error(GLuint shader_id)`](https://github.com/neuromorphic-paris/chameleon/blob/dae8fc605568b591013411b67c3a379efaf4b6ee/source/delta_t_display.hpp#L374) but unfortunately with my skills I can not debug further.

P.S. I am not sure if this helps but I am running Ubuntu 18.04 with a NVIDIA GeForce GTX 1050 TI mobile.

Cheers,
Fanpeng

**Comment by aMarcireau** [comment]
Hi Fanpeng,

I updated the underlying Chameleon library (https://github.com/neuromorphic-paris/chameleon/commit/6c3c0ffffee7cb469af4a38a7cffdf7f469ea00e), hopefully solving the problem. However, I don't have access to a Nvidia GPU, thus I could not test this patch.

To update your local "tutorials" repository, you need to run:
```sh
git pull
git submodule update
```

Let me know if it helps.

Cheers,
Alex

**Comment by fanpeng-kong** [comment]
Thanks for the quick response, Alex. I just tested with the updated Chameleon library and it indeed fixed the problem.

Great work on the framework BTW and I hope it can get more attention soon!
